#!/usr/bin/env bash
sleep 1
killall xdg-desktop-portal
killall xdg-desktop-portal-gtk
killall xdg-desktop-portal-wlr
/usr/lib*/xdg-desktop-portal-wlr &
/usr/lib*/xdg-desktop-portal-gtk &
sleep 2
/usr/lib*/xdg-desktop-portal &
